-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 22:24:07 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


--

CREATE DATABASE IF NOT EXISTS `compumake`

DEFAULT CHARACTER SET utf8 

COLLATE utf8_general_ci;
-- -----------------------------------------------------
-- Schema dbo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbo` ;

-- -----------------------------------------------------
-- Schema dbo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbo` ;
USE `dbo` ;

-- -----------------------------------------------------
-- Table `dbo`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`uf` (
  `uf` VARCHAR(2) NOT NULL COMMENT '',
  `estado` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`uf`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`municipio` (
  `municipio_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `municipio` VARCHAR(250) NOT NULL COMMENT '',
  `uf` VARCHAR(2) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`municipio_id`)  COMMENT '',
  INDEX `fk_municipio_uf_idx` (`uf` ASC)  COMMENT '',
  CONSTRAINT `fk_municipio_uf`
    FOREIGN KEY (`uf`)
    REFERENCES `dbo`.`uf` (`uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`template` (
  `template_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `html` VARCHAR(8000) NULL COMMENT '',
  PRIMARY KEY (`template_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`evento_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`evento_status` (
  `evento_status_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`evento_status_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`evento` (
  `evento_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `evento_status_id` INT NULL COMMENT '',
  `titulo` VARCHAR(250) NOT NULL COMMENT '',
  `data_inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '		',
  `data_fim` TIMESTAMP NOT NULL COMMENT '',
  `cep` VARCHAR(8) NULL COMMENT '',
  `logradouro` VARCHAR(250) NULL COMMENT '',
  `numero` VARCHAR(100) NULL COMMENT '',
  `complemento` VARCHAR(100) NULL COMMENT '',
  `bairro` VARCHAR(250) NULL COMMENT '',
  `municipio_id` INT NULL COMMENT '',
  `uf_id` INT NULL COMMENT '',
  `descricao` VARCHAR(8000) NULL COMMENT '',
  `status` TINYINT NULL COMMENT '',
  `logo` BLOB NULL COMMENT '',
  `fundo` BLOB NULL COMMENT '',
  `html` VARCHAR(8000) NULL COMMENT '',
  `cor` VARCHAR(6) NULL COMMENT '',
  `template_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`evento_id`)  COMMENT '',
  INDEX `fk_evento_municipio_idx` (`municipio_id` ASC)  COMMENT '',
  INDEX `fk_evento_evento_status_idx` (`evento_status_id` ASC)  COMMENT '',
  CONSTRAINT `fk_evento_municipio`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `dbo`.`municipio` (`municipio_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evento_template`
    FOREIGN KEY ()
    REFERENCES `dbo`.`template` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_evento_status`
    FOREIGN KEY (`evento_status_id`)
    REFERENCES `dbo`.`evento_status` (`evento_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`staff` (
  `staff_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `address_id` SMALLINT UNSIGNED NOT NULL COMMENT '',
  `picture` BLOB NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `store_id` TINYINT UNSIGNED NOT NULL COMMENT '',
  `active` TINYINT(1) NOT NULL DEFAULT TRUE COMMENT '',
  `username` VARCHAR(16) NOT NULL COMMENT '',
  `password` VARCHAR(40) BINARY NULL DEFAULT NULL COMMENT '',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`staff_id`)  COMMENT '',
  INDEX `idx_fk_address_id` (`address_id` ASC)  COMMENT '',
  CONSTRAINT `fk_staff_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `dbo`.`uf` (`uf`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`contato` (
  `contato_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(250) NOT NULL COMMENT '',
  `tratamento` VARCHAR(45) NULL COMMENT '',
  `apelido` VARCHAR(45) NULL COMMENT '',
  `cpf` VARCHAR(11) NULL COMMENT '',
  `nascimento` TIMESTAMP NULL COMMENT '',
  `foto` BLOB NULL COMMENT '',
  PRIMARY KEY (`contato_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`empresa` (
  `empresa_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_fantasia` VARCHAR(250) NOT NULL COMMENT '',
  `razao_social` VARCHAR(250) NULL COMMENT '',
  `cnpj` VARCHAR(14) NULL COMMENT '',
  `fundacao` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`empresa_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`organizador` (
  `organizador_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contato_id` INT NULL COMMENT '',
  `empresa_id` INT NULL COMMENT '',
  PRIMARY KEY (`organizador_id`)  COMMENT '',
  INDEX `fk_organizador_contato_idx` (`contato_id` ASC)  COMMENT '',
  INDEX `fk_organizador_empresa_idx` (`empresa_id` ASC)  COMMENT '',
  CONSTRAINT `fk_organizador_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `dbo`.`contato` (`contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizador_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `dbo`.`empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`evento_organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`evento_organizador` (
  `evento_id` INT NOT NULL COMMENT '',
  `organizador_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`evento_id`, `organizador_id`)  COMMENT '',
  INDEX `fk_evento_organizador_organizador_idx` (`organizador_id` ASC)  COMMENT '',
  CONSTRAINT `fk_evento_organizador_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `dbo`.`evento` (`evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_organizador_organizador`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `dbo`.`organizador` (`organizador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`perfil` (
  `perfil_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `perfil` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`perfil_id`)  COMMENT '',
  INDEX `perfil_id` ()  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`operador` (
  `operador_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contato_id` INT NULL COMMENT '',
  `perfil_id` INT NULL COMMENT '',
  `login` VARCHAR(250) NULL COMMENT '',
  `senha` VARCHAR(36) NULL COMMENT '',
  `status` TINYINT NULL COMMENT '',
  `ultimo_acesso` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`operador_id`)  COMMENT '',
  INDEX `fk_operador_contato_idx` (`contato_id` ASC)  COMMENT '',
  INDEX `fk_operador_perfil_idx` (`perfil_id` ASC)  COMMENT '',
  CONSTRAINT `fk_operador_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `dbo`.`contato` (`contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operador_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `dbo`.`perfil` (`perfil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`telefone` (
  `telefone_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contato_id` INT NULL COMMENT '',
  `empresa_id` INT NULL COMMENT '',
  `ddi` VARCHAR(3) NOT NULL DEFAULT '+55' COMMENT '',
  `ddd` VARCHAR(3) NULL DEFAULT '031' COMMENT '',
  `telefone` VARCHAR(45) NULL COMMENT '',
  `observacao` VARCHAR(1000) NULL COMMENT '',
  `ativo` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`telefone_id`)  COMMENT '',
  INDEX `fk_telefone_contato_idx` (`contato_id` ASC)  COMMENT '',
  INDEX `fk_telefone_empresa_idx` (`empresa_id` ASC)  COMMENT '',
  CONSTRAINT `fk_telefone_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `dbo`.`contato` (`contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `dbo`.`empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`email` (
  `email_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contato_id` INT NULL COMMENT '',
  `empresa_id` INT NULL COMMENT '',
  `email` VARCHAR(3) NOT NULL DEFAULT '+55' COMMENT '',
  `observacao` VARCHAR(1000) NULL COMMENT '',
  `ativo` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`email_id`)  COMMENT '',
  INDEX `fk_email_contato_idx` (`contato_id` ASC)  COMMENT '',
  INDEX `fk_email_empresa_idx` (`empresa_id` ASC)  COMMENT '',
  CONSTRAINT `fk_email_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `dbo`.`contato` (`contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `dbo`.`empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`banner` (
  `banner_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `template_id` INT NOT NULL COMMENT '',
  `imagem` BLOB NOT NULL COMMENT '',
  `titulo` VARCHAR(250) NULL COMMENT '',
  `descricao` VARCHAR(1000) NULL COMMENT '',
  `alinhamento` TINYINT NULL COMMENT '',
  `ativo` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`banner_id`)  COMMENT '',
  CONSTRAINT `fk_banner_template`
    FOREIGN KEY ()
    REFERENCES `dbo`.`template` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`evento_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`evento_perfil` (
  `evento_perfil_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `evento_id` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(250) NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  `valor` DECIMAL(15,2) NOT NULL DEFAULT 0 COMMENT '',
  `data_inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `data_fim` TIMESTAMP NULL COMMENT '',
  `minimo` INT NULL DEFAULT 1 COMMENT '',
  `maximo` INT NULL COMMENT '',
  `antecipado_valor` DECIMAL(15,2) NULL COMMENT '',
  `antecipado_inicio` TIMESTAMP NULL COMMENT '',
  `antecipado_fim` TIMESTAMP NULL COMMENT '',
  `descricao` VARCHAR(1000) NULL COMMENT '',
  `restrito` BIT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`evento_perfil_id`)  COMMENT '',
  INDEX `fk_template_evento_idx` (`evento_id` ASC)  COMMENT '',
  CONSTRAINT `fk_evento_perfil_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `dbo`.`evento` (`evento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`formulario` (
  `formulario_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `evento_perfil_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`formulario_id`)  COMMENT '',
  INDEX `fk_formulario_evento_perfil_idx` (`evento_perfil_id` ASC)  COMMENT '',
  CONSTRAINT `fk_formulario_evento_perfil`
    FOREIGN KEY (`evento_perfil_id`)
    REFERENCES `dbo`.`evento_perfil` (`evento_perfil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`formulario_campo_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`formulario_campo_tipo` (
  `formulario_campo_tipo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`formulario_campo_tipo_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`formulario_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`formulario_campo` (
  `formulario_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `formulario_campo_id` INT NOT NULL COMMENT '',
  `formulario_campo_tipo_id` INT NOT NULL COMMENT '',
  `campo` VARCHAR(1000) NOT NULL COMMENT '',
  `obrigatorio` BIT NOT NULL DEFAULT 0 COMMENT '',
  `duplicado` BIT NOT NULL DEFAULT 1 COMMENT '',
  `descricao` VARCHAR(8000) NULL COMMENT '',
  `dependencia_formulario_campo_id` INT NULL COMMENT '',
  PRIMARY KEY (`formulario_id`, `obrigatorio`)  COMMENT '',
  INDEX `fk_formulario_opcoes_formulario_idx` (`formulario_campo_id` ASC)  COMMENT '',
  INDEX `fk_formulario_campo_tipo_idx` (`formulario_campo_tipo_id` ASC)  COMMENT '',
  INDEX `fk_formulario_campo_dependencia_idx` (`dependencia_formulario_campo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_formulario_campo_formulario`
    FOREIGN KEY (`formulario_campo_id`)
    REFERENCES `dbo`.`formulario` (`formulario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_campo_tipo`
    FOREIGN KEY (`formulario_campo_tipo_id`)
    REFERENCES `dbo`.`formulario_campo_tipo` (`formulario_campo_tipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_campo_dependencia`
    FOREIGN KEY (`dependencia_formulario_campo_id`)
    REFERENCES `dbo`.`formulario_campo` (`formulario_campo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`formulario_campo_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`formulario_campo_alternativa` (
  `formulario_campo_alteranativa_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `formulario_campo_id` INT NOT NULL COMMENT '',
  `alternativa` VARCHAR(1000) NOT NULL COMMENT '',
  PRIMARY KEY (`formulario_campo_alteranativa_id`)  COMMENT '',
  INDEX `fk_formulario_campo_alternativa_idx` (`formulario_campo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_formulario_campo_alternativa`
    FOREIGN KEY (`formulario_campo_id`)
    REFERENCES `dbo`.`formulario_campo` (`formulario_campo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`participante_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`participante_status` (
  `participante_status_id` TINYINT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` VARCHAR(250) NULL COMMENT '',
  PRIMARY KEY (`participante_status_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`participante` (
  `participante_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `contato_id` INT NULL COMMENT '',
  `formulario_id` INT NULL COMMENT '',
  `participante_status_id` TINYINT NULL COMMENT '',
  `data_inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `data_conclusao` TIMESTAMP NULL COMMENT '',
  `data_checkin` TIMESTAMP NULL COMMENT '',
  `chave` VARCHAR(36) NOT NULL DEFAULT 'UUID()' COMMENT '',
  PRIMARY KEY (`participante_id`, `chave`)  COMMENT '',
  INDEX `fk_participante_formulario_idx` (`formulario_id` ASC)  COMMENT '',
  INDEX `fk_participante_participante_status_idx` (`participante_status_id` ASC)  COMMENT '',
  INDEX `fk_participante_contato_idx` (`contato_id` ASC)  COMMENT '',
  CONSTRAINT `fk_participante_formulario`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `dbo`.`formulario` (`formulario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_participante_status`
    FOREIGN KEY (`participante_status_id`)
    REFERENCES `dbo`.`participante_status` (`participante_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `dbo`.`contato` (`contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`participante_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`participante_campo` (
  `participante_campo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `formulario_campo_id` INT NOT NULL COMMENT '',
  `participante_id` INT NOT NULL COMMENT '',
  `valor` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`participante_campo_id`)  COMMENT '',
  INDEX `fk_participante_campo_formulario_campo_idx` (`formulario_campo_id` ASC)  COMMENT '',
  INDEX `fk_participante_campo_participante_formulario_idx` (`participante_id` ASC)  COMMENT '',
  CONSTRAINT `fk_participante_campo_formulario_campo`
    FOREIGN KEY (`formulario_campo_id`)
    REFERENCES `dbo`.`formulario_campo` (`formulario_campo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_campo_participante_formulario`
    FOREIGN KEY (`participante_id`)
    REFERENCES `dbo`.`participante` (`participante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`participante_campo_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`participante_campo_alternativa` (
  `participante_campo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `formulario_campo_alternativa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`participante_campo_id`)  COMMENT '',
  INDEX `fk_participante_campo_alternativa_formulario_campo_alternat_idx` (`formulario_campo_alternativa` ASC)  COMMENT '',
  CONSTRAINT `fk_participante_campo_alternativa_formulario_campo_alternativa`
    FOREIGN KEY (`formulario_campo_alternativa`)
    REFERENCES `dbo`.`formulario_campo_alternativa` (`formulario_campo_alteranativa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_campo_alternativa_participante_campo`
    FOREIGN KEY (`participante_campo_id`)
    REFERENCES `dbo`.`participante_campo` (`participante_campo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`tipo_pagamento` (
  `tipo_pagamento_id` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`tipo_pagamento_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`status_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`status_pagamento` (
  `status_pagamento_id` TINYINT NOT NULL COMMENT '',
  `titulo` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`status_pagamento_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`venda` (
  `venda_id` INT NOT NULL COMMENT '',
  `participante_id` INT NOT NULL COMMENT '',
  `tipo_pagamento_id` INT NULL COMMENT '',
  `status_pagamento_id` TINYINT NULL COMMENT '',
  `valor` DECIMAL(15,2) NOT NULL COMMENT '',
  `desconto` DECIMAL(15,2) NULL COMMENT '',
  PRIMARY KEY (`venda_id`)  COMMENT '',
  INDEX `fk_venda_participante_idx` (`participante_id` ASC)  COMMENT '',
  INDEX `fk_venda_tipo_pagamento_idx` (`tipo_pagamento_id` ASC)  COMMENT '',
  INDEX `fk_venda_status_pagamento_idx` (`status_pagamento_id` ASC)  COMMENT '',
  CONSTRAINT `fk_venda_participante`
    FOREIGN KEY (`participante_id`)
    REFERENCES `dbo`.`participante` (`participante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_tipo_pagamento`
    FOREIGN KEY (`tipo_pagamento_id`)
    REFERENCES `dbo`.`tipo_pagamento` (`tipo_pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_status_pagamento`
    FOREIGN KEY (`status_pagamento_id`)
    REFERENCES `dbo`.`status_pagamento` (`status_pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`cupom_desconto` (
  `cupom_desconto_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `evento_perfil_id` INT NOT NULL COMMENT '',
  `data_inicio` TIMESTAMP NULL COMMENT '',
  `data_fim` TIMESTAMP NULL COMMENT '',
  `valor` DECIMAL(10,2) NULL COMMENT '',
  `codigo` VARCHAR(250) NOT NULL COMMENT '',
  PRIMARY KEY (`cupom_desconto_id`)  COMMENT '',
  INDEX `fk_formulario_evento_perfil_idx` (`evento_perfil_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cupom_desconto`
    FOREIGN KEY (`evento_perfil_id`)
    REFERENCES `dbo`.`evento_perfil` (`evento_perfil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbo`.`venda_cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`venda_cupom_desconto` (
  `venda_id` INT NOT NULL COMMENT '',
  `cupom_desconto_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`venda_id`)  COMMENT '',
  INDEX `fk_venda_cupom_desconto_cupom_desconto_idx` (`cupom_desconto_id` ASC)  COMMENT '',
  CONSTRAINT `fk_venda_cupom_desconto_venda`
    FOREIGN KEY (`venda_id`)
    REFERENCES `dbo`.`venda` (`venda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cupom_desconto_cupom_desconto`
    FOREIGN KEY (`cupom_desconto_id`)
    REFERENCES `dbo`.`cupom_desconto` (`cupom_desconto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
