-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 22:24:07 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eventos` ;

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos` 
DEFAULT CHARACTER SET utf8 
COLLATE utf8_general_ci;
USE `eventos` ;

-- -----------------------------------------------------
-- Table `eventos`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`uf` (
  `uf` VARCHAR(2) NOT NULL ,
  `estado` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`uf`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `municipio` VARCHAR(250) NOT NULL ,
  `uf` VARCHAR(2) NOT NULL ,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_municipio_uf_idx` (`uf` ASC)  ,
  CONSTRAINT `fk_municipio_uf`
    FOREIGN KEY (`uf`)
    REFERENCES `eventos`.`uf` (`uf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`templates` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `html` VARCHAR(8000) NULL ,
  PRIMARY KEY (`id`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`evento_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`evento_status` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `status` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`id`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `evento_status_id` INT NULL ,
  `titulo` VARCHAR(250) NOT NULL ,
  `data_inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `data_fim` TIMESTAMP NULL,
  `cep` VARCHAR(8) NULL ,
  `logradouro` VARCHAR(250) NULL ,
  `numero` VARCHAR(100) NULL ,
  `complemento` VARCHAR(100) NULL ,
  `bairro` VARCHAR(250) NULL ,
  `municipio_id` INT NULL ,
  `uf_id` INT NULL ,
  `descricao` VARCHAR(8000) NULL ,
  `status` TINYINT NULL ,
  `logo` BLOB NULL ,
  `fundo` BLOB NULL ,
  `html` VARCHAR(8000) NULL ,
  `cor` VARCHAR(6) NULL ,
  `template_id` INT NOT NULL ,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_municipio_idx` (`municipio_id` ASC),
  INDEX `fk_evento_evento_status_idx` (`evento_status_id` ASC),
  CONSTRAINT `fk_evento_municipio`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `eventos`.`municipio` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_evento_evento_status`
    FOREIGN KEY (`evento_status_id`)
    REFERENCES `eventos`.`evento_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`contatos` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `nome` VARCHAR(250) NOT NULL ,
  `tratamento` VARCHAR(45) NULL ,
  `apelido` VARCHAR(45) NULL ,
  `cpf` VARCHAR(11) NULL ,
  `nascimento` TIMESTAMP NULL ,
  `foto` BLOB NULL ,
  PRIMARY KEY (`id`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `nome_fantasia` VARCHAR(250) NOT NULL ,
  `razao_social` VARCHAR(250) NULL ,
  `cnpj` VARCHAR(14) NULL ,
  `fundacao` TIMESTAMP NULL ,
  PRIMARY KEY (`id`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`organizadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`organizadores` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `contato_id` INT NULL ,
  `empresa_id` INT NULL ,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_organizador_contato_idx` (`contato_id` ASC)  ,
  INDEX `fk_organizador_empresa_idx` (`empresa_id` ASC)  ,
  CONSTRAINT `fk_organizador_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `eventos`.`contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizador_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `eventos`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`evento_organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`evento_organizadores` (
  `evento_id` INT NOT NULL ,
  `organizador_id` INT NOT NULL ,
  PRIMARY KEY (`evento_id`, `organizador_id`)  ,
  INDEX `fk_evento_organizador_organizador_idx` (`organizador_id` ASC)  ,
  CONSTRAINT `fk_evento_organizador_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `eventos`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_organizador_organizador`
    FOREIGN KEY (`organizador_id`)
    REFERENCES `eventos`.`organizadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `perfil` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`operador` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `contato_id` INT NULL ,
  `perfil_id` INT NULL ,
  `login` VARCHAR(250) NULL ,
  `senha` VARCHAR(36) NULL ,
  `status` TINYINT NULL ,
  `ultimo_acesso` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_operador_contato_idx` (`contato_id` ASC)  ,
  INDEX `fk_operador_perfil_idx` (`perfil_id` ASC)  ,
  CONSTRAINT `fk_operador_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `eventos`.`contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operador_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `eventos`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `contato_id` INT NULL ,
  `empresa_id` INT NULL ,
  `ddi` VARCHAR(3) NOT NULL DEFAULT '+55' ,
  `ddd` VARCHAR(3) NULL DEFAULT '031' ,
  `telefone` VARCHAR(45) NULL ,
  `observacao` VARCHAR(1000) NULL ,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_telefone_contato_idx` (`contato_id` ASC)  ,
  INDEX `fk_telefone_empresa_idx` (`empresa_id` ASC)  ,
  CONSTRAINT `fk_telefone_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `eventos`.`contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `eventos`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`email` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `contato_id` INT NULL ,
  `empresa_id` INT NULL ,
  `email` VARCHAR(3) NOT NULL DEFAULT '+55' ,
  `observacao` VARCHAR(1000) NULL ,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_email_contato_idx` (`contato_id` ASC)  ,
  INDEX `fk_email_empresa_idx` (`empresa_id` ASC)  ,
  CONSTRAINT `fk_email_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `eventos`.`contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `eventos`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`banner` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `template_id` INT NOT NULL ,
  `imagem` BLOB NOT NULL ,
  `titulo` VARCHAR(250) NULL ,
  `descricao` VARCHAR(1000) NULL ,
  `alinhamento` TINYINT NULL ,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1 ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`evento_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`evento_perfis` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `evento_id` INT NOT NULL ,
  `titulo` VARCHAR(250) NOT NULL ,
  descricao VARCHAR(1000) NULL,
  periodo tinyint(1) NOT NULL DEFAULT 1,
  `data_inicio` TIMESTAMP NULL ,
  `data_fim` TIMESTAMP NULL ,
  limite_participantes tinyint(1) NOT NULL DEFAULT 0,
  `quantidade` INT NOT NULL ,
  `minimo` INT NULL DEFAULT 1 ,
  `maximo` INT NULL ,
  
  exigir_pagamento TINYINT(1) NOT NULL DEFAULT 0,
  `valor` DECIMAL(15,2) NOT NULL DEFAULT 0 ,
  
  `antecipado_valor` DECIMAL(15,2) NULL ,
  `antecipado_inicio` TIMESTAMP NULL ,
  `antecipado_fim` TIMESTAMP NULL ,
  
  desconto_grupos TINYINT(1) NOT NULL DEFAULT 0,
  desconto_grupo_valor FLOAT NULL,
  desconto_grupo_tipo TINYINT(1) NULL,
  desconto_grupo_min INT NULL,
  desconto_grupo_descricao VARCHAR(1000),
  
  `restrito` tinyint(1) NULL DEFAULT 0 ,
  captcha tinyint(1) NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_template_evento_idx` (`evento_id` ASC)  ,
  CONSTRAINT `fk_evento_perfil_evento`
    FOREIGN KEY (`evento_id`)
    REFERENCES `eventos`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`cupom_descontos` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `evento_perfil_id` INT NOT NULL ,
  `data_inicio` TIMESTAMP NULL ,
  `data_fim` TIMESTAMP NULL ,
  `valor` FLOAT NULL ,
  valor_tipo TINYINT(1) NULL,
  `codigo` VARCHAR(250) NOT NULL ,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_formulario_evento_perfil_idx` (`evento_perfil_id` ASC)  ,
  CONSTRAINT `fk_cupom_desconto`
    FOREIGN KEY (`evento_perfil_id`)
    REFERENCES `eventos`.`evento_perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`formulario_campo_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`campo_tipos` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `tipo` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`id`)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`formulario_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`campos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evento_perfil_id` INT NOT NULL  ,
  `campo_tipo_id` INT NOT NULL ,
  `campo` VARCHAR(1000) NOT NULL ,
  `obrigatorio` tinyint(1) NOT NULL DEFAULT 0 ,
  `duplicado` tinyint(1) NOT NULL DEFAULT 1 ,
  `descricao` VARCHAR(8000) NULL ,
	ordem TINYINT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_campo_idx` (`evento_perfil_id` ASC)  ,
  INDEX `fk_campo_tipo_idx` (`campo_tipo_id` ASC)  ,
  CONSTRAINT `fk_campo_evento_perfis`
    FOREIGN KEY (`evento_perfil_id`)
    REFERENCES `eventos`.`evento_perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campo_campo_tipo`
    FOREIGN KEY (`campo_tipo_id`)
    REFERENCES `eventos`.`campo_tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`formulario_campo_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`campo_alternativas` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `campo_id` INT NOT NULL ,
  `alternativa` VARCHAR(1000) NOT NULL ,
	ordem TINYINT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id`)  ,
  INDEX `fk_campo_alternativa_idx` (`campo_id` ASC)  ,
  CONSTRAINT `fk_campo_alternativa_campo`
    FOREIGN KEY (`campo_id`)
    REFERENCES `eventos`.`campos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`formulario_campo_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`campo_condicoes` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `campo_id` INT NOT NULL ,
  `condicao` VARCHAR(2) NOT NULL ,
  `valor` VARCHAR(250) NOT NULL ,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_campo_condicoes_idx` (`campo_id` ASC)  ,
  CONSTRAINT `fk_campo_condicoes_campo`
    FOREIGN KEY (`campo_id`)
    REFERENCES `eventos`.`campos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `eventos`.`participante_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`participante_status` (
  `participante_status_id` TINYINT NOT NULL AUTO_INCREMENT ,
  `status` VARCHAR(250) NULL ,
  PRIMARY KEY (`participante_status_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`participante` (
  `participante_id` INT NOT NULL AUTO_INCREMENT ,
  `contato_id` INT NULL ,
  `formulario_id` INT NULL ,
  `participante_status_id` TINYINT NULL ,
  `data_inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  `data_conclusao` TIMESTAMP NULL ,
  `data_checkin` TIMESTAMP NULL ,
  `chave` VARCHAR(36) NOT NULL DEFAULT 'UUID()' ,
  PRIMARY KEY (`participante_id`, `chave`)  ,
  INDEX `fk_participante_formulario_idx` (`formulario_id` ASC)  ,
  INDEX `fk_participante_participante_status_idx` (`participante_status_id` ASC)  ,
  INDEX `fk_participante_contato_idx` (`contato_id` ASC)  ,
  CONSTRAINT `fk_participante_formulario`
    FOREIGN KEY (`formulario_id`)
    REFERENCES `eventos`.`formulario` (`formulario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_participante_status`
    FOREIGN KEY (`participante_status_id`)
    REFERENCES `eventos`.`participante_status` (`participante_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_contato`
    FOREIGN KEY (`contato_id`)
    REFERENCES `eventos`.`contatos` (`contato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`participante_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`participante_campo` (
  `participante_campo_id` INT NOT NULL AUTO_INCREMENT ,
  `formulario_campo_id` INT NOT NULL ,
  `participante_id` INT NOT NULL ,
  `valor` VARCHAR(1000) NULL ,
  PRIMARY KEY (`participante_campo_id`)  ,
  INDEX `fk_participante_campo_formulario_campo_idx` (`formulario_campo_id` ASC)  ,
  INDEX `fk_participante_campo_participante_formulario_idx` (`participante_id` ASC)  ,
  CONSTRAINT `fk_participante_campo_formulario_campo`
    FOREIGN KEY (`formulario_campo_id`)
    REFERENCES `eventos`.`formulario_campo` (`formulario_campo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_campo_participante_formulario`
    FOREIGN KEY (`participante_id`)
    REFERENCES `eventos`.`participante` (`participante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`participante_campo_alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`participante_campo_alternativa` (
  `participante_campo_id` INT NOT NULL AUTO_INCREMENT ,
  `formulario_campo_alternativa` INT NOT NULL ,
  PRIMARY KEY (`participante_campo_id`)  ,
  INDEX `fk_participante_campo_alternativa_formulario_campo_alternat_idx` (`formulario_campo_alternativa` ASC)  ,
  CONSTRAINT `fk_participante_campo_alternativa_formulario_campo_alternativa`
    FOREIGN KEY (`formulario_campo_alternativa`)
    REFERENCES `eventos`.`formulario_campo_alternativa` (`formulario_campo_alteranativa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_campo_alternativa_participante_campo`
    FOREIGN KEY (`participante_campo_id`)
    REFERENCES `eventos`.`participante_campo` (`participante_campo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`tipo_pagamento` (
  `tipo_pagamento_id` INT NOT NULL ,
  `titulo` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`tipo_pagamento_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`status_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`status_pagamento` (
  `status_pagamento_id` TINYINT NOT NULL ,
  `titulo` VARCHAR(250) NOT NULL ,
  PRIMARY KEY (`status_pagamento_id`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eventos`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`venda` (
  `venda_id` INT NOT NULL ,
  `participante_id` INT NOT NULL ,
  `tipo_pagamento_id` INT NULL ,
  `status_pagamento_id` TINYINT NULL ,
  `valor` DECIMAL(15,2) NOT NULL ,
  `desconto` DECIMAL(15,2) NULL ,
  PRIMARY KEY (`venda_id`)  ,
  INDEX `fk_venda_participante_idx` (`participante_id` ASC)  ,
  INDEX `fk_venda_tipo_pagamento_idx` (`tipo_pagamento_id` ASC)  ,
  INDEX `fk_venda_status_pagamento_idx` (`status_pagamento_id` ASC)  ,
  CONSTRAINT `fk_venda_participante`
    FOREIGN KEY (`participante_id`)
    REFERENCES `eventos`.`participante` (`participante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_tipo_pagamento`
    FOREIGN KEY (`tipo_pagamento_id`)
    REFERENCES `eventos`.`tipo_pagamento` (`tipo_pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_status_pagamento`
    FOREIGN KEY (`status_pagamento_id`)
    REFERENCES `eventos`.`status_pagamento` (`status_pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `eventos`.`venda_cupom_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`venda_cupom_desconto` (
  `venda_id` INT NOT NULL ,
  `cupom_desconto_id` INT NOT NULL ,
  PRIMARY KEY (`venda_id`)  ,
  INDEX `fk_venda_cupom_desconto_cupom_desconto_idx` (`cupom_desconto_id` ASC)  ,
  CONSTRAINT `fk_venda_cupom_desconto_venda`
    FOREIGN KEY (`venda_id`)
    REFERENCES `eventos`.`venda` (`venda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cupom_desconto_cupom_desconto`
    FOREIGN KEY (`cupom_desconto_id`)
    REFERENCES `eventos`.`cupom_desconto` (`cupom_desconto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE `roles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL,
  `role_id` int(10) unsigned NOT NULL DEFAULT '1',
  `last_login` timestamp NULL DEFAULT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_role_id_foreign` (`role_id`),
  CONSTRAINT `users_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO eventos.roles
(name,description,created_at,updated_at)
SELECT name,description,created_at,updated_at
FROM talentos.roles;

INSERT INTO eventos.users
(name,email,password,remember_token,created_at,updated_at,role_id,last_login,ativo)
SELECT name,email,password,remember_token,created_at,updated_at,5,last_login,ativo
FROM talentos.users;

ALTER TABLE eventos.eventos
	ADD  evento_categoria_id INT;
		
ALTER TABLE eventos.eventos
	ADD evento_tipo_id INT;
        
ALTER TABLE eventos.eventos
	ADD gllpLatitude FLOAT;
        
ALTER TABLE eventos.eventos
	ADD gllpLongitude FLOAT;
    

ALTER TABLE eventos.eventos
	ADD municipio VARCHAR(250);
    
ALTER TABLE eventos.eventos
	CHANGE uf_id uf varchar(2);
    
ALTER TABLE eventos.eventos
	ADD `created_at` timestamp NULL;

ALTER TABLE eventos.eventos
	ADD updated_at timestamp NULL;
    
ALTER TABLE eventos.contatos
	ADD `created_at` timestamp NULL;

ALTER TABLE eventos.contatos
	ADD updated_at timestamp NULL;

ALTER TABLE eventos.organizadores
	ADD `created_at` timestamp NULL;

ALTER TABLE eventos.organizadores
	ADD updated_at timestamp NULL;
    
    
ALTER TABLE eventos.empresas
	ADD `created_at` timestamp NULL;

ALTER TABLE eventos.empresas
	ADD updated_at timestamp NULL;
    
    
ALTER TABLE eventos.evento_organizadores
	ADD `created_at` timestamp NULL;

ALTER TABLE eventos.evento_organizadores
	ADD updated_at timestamp NULL;
    
ALTER TABLE eventos.organizadores
	ADD descricao VARCHAR(1000);
    
ALTER TABLE eventos.eventos
	ADD dia_inteiro TINYINT(1);
    
ALTER TABLE eventos.eventos
	ADD gllpZoom TINYINT(4);
    
SELECT * FROM eventos.contatos;
SELECT * FROM eventos.organizadores;
SELECT * FROM eventos.evento_organizadores;

drop table arquivos;

CREATE TABLE `arquivos` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `file` longblob NOT NULL,
  `mime` varchar(255) DEFAULT NULL,
  `size` int(10) unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

USE eventos;

ALTER TABLE eventos DROP COLUMN logo;
ALTER TABLE eventos DROP COLUMN fundo;
ALTER TABLE eventos DROP COLUMN html;

ALTER TABLE eventos
	ADD COLUMN logo_arquivo_id INT NULL,
    ADD FOREIGN KEY FK_eventos_arquivos_logo (logo_arquivo_id)
		REFERENCES arquivos(id);
        
ALTER TABLE eventos
	ADD COLUMN banner_arquivo_id INT NULL,
    ADD FOREIGN KEY FK_eventos_arquivos_banner (banner_arquivo_id)
		REFERENCES arquivos(id);

ALTER TABLE eventos
	ADD COLUMN background_arquivo_id INT NULL,
    ADD FOREIGN KEY FK_eventos_arquivos_background (background_arquivo_id)
		REFERENCES arquivos(id);

USE eventos;
ALTER TABLE arquivos ADD COLUMN extensao VARCHAR(20) NULL;

ALTER TABLE eventos DROP COLUMN cor_texto;
ALTER TABLE eventos DROP COLUMN cor_predominante;
ALTER TABLE eventos DROP COLUMN cor_fundo;

ALTER TABLE eventos ADD COLUMN cor_texto VARCHAR(20);
ALTER TABLE eventos ADD COLUMN cor_predominante VARCHAR(20);
ALTER TABLE eventos ADD COLUMN cor_fundo VARCHAR(20);
ALTER TABLE eventos ADD COLUMN facebook VARCHAR(2000);
ALTER TABLE eventos ADD COLUMN twitter VARCHAR(2000);
ALTER TABLE eventos ADD COLUMN youtube VARCHAR(2000);

ALTER TABLE eventos ADD COLUMN slug VARCHAR(2000);

USE eventos;
ALTER TABLE eventos ADD COLUMN local VARCHAR(250);

CREATE TABLE IF NOT EXISTS `eventos`.`evento_perfil_grupos` (
  id INT NOT NULL AUTO_INCREMENT ,
  evento_perfil_id INT NOT NULL,
  titulo VARCHAR(250) NOT NULL,
  ordem smallint NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (`id`)  ,
  INDEX `ix_evento_perfil_grupos_perfil` (`evento_perfil_id` ASC),
  CONSTRAINT `fk_evento_perfil_grupos_perfil`
    FOREIGN KEY (`evento_perfil_id`)
    REFERENCES `eventos`.`evento_perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

ALTER TABLE evento_perfil_grupos ADD COLUMN ordem smallint NULL;

DELETE FROM campo_alternativas;
DELETE FROM campos;
DELETE FROM evento_perfis;
DELETE FROM evento_organizadores WHERE evento_id < 10;
DELETE FROM eventos WHERE id < 10;
ALTER TABLE campos DROP COLUMN evento_perfil_grupo_id;

ALTER TABLE campos
	ADD COLUMN evento_perfil_grupo_id INT NOT NULL,
    ADD CONSTRAINT FOREIGN KEY FK_campos_evento_perfil_grupos(evento_perfil_grupo_id)
		REFERENCES evento_perfil_grupos (id);
        
USE eventos;
SELECT * FROM evento_perfil_grupos;

SELECT * FROM campos;

ALTER TABLE campos
	ADD COLUMN tamanho smallint NOT NULL DEFAULT 1;
    
SELECT * FROM campos;
SELECT * FROM campo_tipos ORDER BY id;
SELECT * FROM campo_alternativas;

SELECT * FROM campos_modelos;
SELECT * FROM campo_condicoes;

UPDATE campos_modelos
SET autocomplete = 1
WHERE classe IN('cnpj', 'cpf', 'cep');

UPDATE